[package]
name = "parquet_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.23"
egui = "0.23"
tokio = { version = "1.29", features = ["macros", "rt-multi-thread"] }
datafusion = "23.0.0"
parquet = "23.0.0"
rfd = "0.13"
poll-promise = "0.3"